### ISSUE TITLE
Привести нотацию имён к единому виду

### ISSUE THREAD

**Issue by cher-nov** [cpp-ru/cpp-ru.github.io#1]
Сейчас на главной странице два имени указаны в порядке "имя-фамилия", а другие два - в порядке "фамилия-имя" (как у [венгров](https://ru.wikipedia.org/wiki/Венгерское_имя) 🙂).

https://github.com/cpp-ru/cpp-ru.github.io/blob/3f34a8471ce555e6ce50924e02955cf09ad60a77/index.html#L147

https://github.com/cpp-ru/cpp-ru.github.io/blob/3f34a8471ce555e6ce50924e02955cf09ad60a77/index.html#L152
https://github.com/cpp-ru/cpp-ru.github.io/blob/3f34a8471ce555e6ce50924e02955cf09ad60a77/index.html#L142

https://github.com/cpp-ru/cpp-ru.github.io/blob/3f34a8471ce555e6ce50924e02955cf09ad60a77/index.html#L160

Мне кажется, было бы неплохо остановиться на каком-то одном варианте. Лучше, на мой взгляд, обычное "имя-фамилия".

**Comment by apolukhin** [comment]
Исправлено в #3
